title: Shiye Zhu's Homepage
page-top-title: Welcome, sweet spring!
top-section-bg-text: <p>Enviernmental Microbiology：<br>Element biogeochemical cycles, <br>Cell stress adaptations</p>
home-subtitle: Shiye Zhu&ensp;|&ensp;朱式业
copyright-text: '&copy; Shiye Zhu 2023-2024. All Rights Reserved.'
