title: Shiye Zhu's Homepage
page-top-title: Shiye Zhu
top-section-bg-text: Enviernmental Microbiology
home-subtitle: Shiye Zhu&ensp;|&ensp;朱式业
copyright-text: '&copy; Shiye Zhu 2023-2024. All Rights Reserved.'
