title: Shiye Zhu's Homepage
page-top-title: Welcome, sweet spring!
top-section-bg-text: Enviernmental Microbiology <p>Elemental Geochemical Cycles</p> Cell Stress Adaptations
home-subtitle: Shiye Zhu&ensp;|&ensp;朱式业
copyright-text: '&copy; Shiye Zhu 2023-2024. All Rights Reserved.'
